title: Jeff Coggshall's blog
tagline: Notes on data, systems, and learning in public.
lang: en
timezone: America/New_York
url: https://voxmenthe.github.io
baseurl: ""
permalink: /:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections:
  posts:
    output: true

navigation:
  - label: Posts
    path: /
  - label: About
    path: /about/

author:
  name: Jeff Coggshall
  email: neutralsphinx@gmail.com
  links:
    - label: GitHub
      url: https://github.com/voxmenthe
    - label: LinkedIn
      url: https://www.linkedin.com/in/jeffcoggshall

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Jeff Coggshall
      comments: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - infra
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - Gemfile.lock
  - .idea

sass:
  style: compressed
